#!/bin/sh

set -e

echo "Git-Hook: running static-analysers and tests before push."
echo

TEST_DB="var/test.db"
if [ ! -s "$TEST_DB" ]; then
  echo "Initializing test database..."
  echo

  rm -f "$TEST_DB"
  php bin/console doctrine:schema:create --env=test --no-interaction
  # php bin/console doctrine:fixtures:load --env=test --no-interaction
fi

composer static-code-check

if [ $? -ne 0 ]; then
  echo "Tests failed. Push aborted."
  exit 1
fi

echo "Push successful."
