#!/bin/sh

echo "Running static-analysers and tests before push..."

TEST_DB="var/test.db"

if [ ! -f "$TEST_DB" ]; then
  echo "Test database not found. Creating..."
  php bin/console doctrine:schema:create --env=test --no-interaction
  # php bin/console doctrine:fixtures:load --env=test --no-interaction
fi

composer static-code-check

if [ $? -ne 0 ]; then
  echo "Tests failed. Push aborted."
  exit 1
fi

echo "Push allowed."
